nuevas_ponderaciones = {'BRENTVIP-50': {'instrumento': 'BRENT', 'tipo_instrumento': 'COMMODITIES', 'tipo': 'COMMODITIES', 'monto_usd': 1.0, 'categoria': 'VIP', 'path': 'CFD Commodities\\Spot\\BRENT', 'moneda_calculo': 'USD', 'precio': 78.481, 'tamanio_contrato': 1000, 'spread_full': 150, 'spread_diff': -50, 'spread_premium': 100, 'spread_vip': 100, 'ponderacion_full': 1.0, 'ponderacion_premium': 0.667, 'ponderacion_vip': 0.667, 'grupos_id': '147, 148', 'fecha_insercion_precio': '2024-01-19 18:05:08.432', 'fecha_insercion_registro': '2024-01-20 11:40:45.217'}, 'BRENTPRE-50': {'instrumento': 'BRENT', 'tipo_instrumento': 'COMMODITIES', 'tipo': 'COMMODITIES', 'monto_usd': 1.0, 'categoria': 'PRE', 'path': 'CFD Commodities\\Spot\\BRENT', 'moneda_calculo': 'USD', 'precio': 78.481, 'tamanio_contrato': 1000, 'spread_full': 150, 'spread_diff': -50, 'spread_premium': 100, 'spread_vip': 100, 'ponderacion_full': 1.0, 'ponderacion_premium': 0.667, 'ponderacion_vip': 0.667, 'grupos_id': '450, 554', 'fecha_insercion_precio': '2024-01-19 18:05:08.432', 'fecha_insercion_registro': '2024-01-20 11:40:45.217'}, 'WTIVIP-50': {'instrumento': 'WTI', 'tipo_instrumento': 'COMMODITIES', 'tipo': 'COMMODITIES', 'monto_usd': 1.0, 'categoria': 'VIP', 'path': 'CFD Commodities\\Spot\\WTI', 'moneda_calculo': 'USD', 'precio': 73.6, 'tamanio_contrato': 1000, 'spread_full': 200, 'spread_diff': -50, 'spread_premium': 150, 'spread_vip': 150, 'ponderacion_full': 1.0, 'ponderacion_premium': 0.75, 'ponderacion_vip': 0.75, 'grupos_id': '147', 'fecha_insercion_precio': '2024-01-19 18:05:08.432', 'fecha_insercion_registro': '2024-01-20 11:40:45.217'}, 'WTIPRE-50': {'instrumento': 'WTI', 'tipo_instrumento': 'COMMODITIES', 'tipo': 'COMMODITIES', 'monto_usd': 1.0, 'categoria': 'PRE', 'path': 'CFD Commodities\\Spot\\WTI', 'moneda_calculo': 'USD', 'precio': 73.6, 'tamanio_contrato': 1000, 'spread_full': 200, 'spread_diff': -50, 'spread_premium': 150, 'spread_vip': 150, 'ponderacion_full': 1.0, 'ponderacion_premium': 0.75, 'ponderacion_vip': 0.75, 'grupos_id': '450, 554', 'fecha_insercion_precio': '2024-01-19 18:05:08.432', 'fecha_insercion_registro': '2024-01-20 11:40:45.217'}, 'WTIVIP0': {'instrumento': 'WTI', 'tipo_instrumento': 'COMMODITIES', 'tipo': 'COMMODITIES', 'monto_usd': 1.0, 'categoria': 'VIP', 'path': 'CFD Commodities\\Spot\\WTI', 'moneda_calculo': 'USD', 'precio': 73.6, 'tamanio_contrato': 1000, 'spread_full': 200, 'spread_diff': 0, 'spread_premium': 200, 'spread_vip': 200, 'ponderacion_full': 1.0, 'ponderacion_premium': 1.1, 'ponderacion_vip': 1.0, 'grupos_id': '148', 'fecha_insercion_precio': '2024-01-19 18:05:08.432', 'fecha_insercion_registro': '2024-01-20 11:40:45.217'}}
viejas_ponderaciones = {'BRENTVIP-50': {'precio': 30.481, 'tamanio_contrato': 1000, 'monto_usd': 1.0, 'ponderacion_full': 1.0, 'ponderacion_premium': 0.667, 'ponderacion_vip': 0.667, 'grupos_id': '147, 148'}, 'BRENTPRE-50': {'precio': 78.481, 'tamanio_contrato': 1000, 'monto_usd': 1.0, 'ponderacion_full': 1.0, 'ponderacion_premium': 0.667, 'ponderacion_vip': 0.667, 'grupos_id': '450, 554'}, 'WTIVIP-50': {'precio': 73.6, 'tamanio_contrato': 1000, 'monto_usd': 1.0, 'ponderacion_full': 1.0, 'ponderacion_premium': 0.75, 'ponderacion_vip': 0.75, 'grupos_id': '147'}, 'WTIPRE-50': {'precio': 73.6, 'tamanio_contrato': 1000, 'monto_usd': 1.0, 'ponderacion_full': 1.0, 'ponderacion_premium': 0.75, 'ponderacion_vip': 0.75, 'grupos_id': '450, 554'}, 'WTIVIP0': {'precio': 73.6, 'tamanio_contrato': 1000, 'monto_usd': 1.0, 'ponderacion_full': 1.0, 'ponderacion_premium': 1.0, 'ponderacion_vip': 1.0, 'grupos_id': '148'}}


update = dict()
no_update = dict()
insert = dict()

for codigo in nuevas_ponderaciones:
    if codigo in viejas_ponderaciones:
        if (viejas_ponderaciones[codigo]['ponderacion_full'] != nuevas_ponderaciones[codigo]['ponderacion_full']
            or viejas_ponderaciones[codigo]['ponderacion_premium'] != nuevas_ponderaciones[codigo]['ponderacion_premium']
            or viejas_ponderaciones[codigo]['ponderacion_vip'] != nuevas_ponderaciones[codigo]['ponderacion_vip']
            or viejas_ponderaciones[codigo]['grupos_id'] != nuevas_ponderaciones[codigo]['grupos_id']
            or viejas_ponderaciones[codigo]['monto_usd'] != nuevas_ponderaciones[codigo]['monto_usd']
            or viejas_ponderaciones[codigo]['precio'] != nuevas_ponderaciones[codigo]['precio']):
            update.update({codigo:nuevas_ponderaciones[codigo]})
        else:
            no_update.update({codigo:nuevas_ponderaciones[codigo]})
    else:
        insert.update({codigo:nuevas_ponderaciones[codigo]})
        
print(f"\n\nNuevo: {[symbol for symbol in insert]}\n\nActualizado: {[symbol for symbol in update]}\n\nNo Actualizado: {[symbol for symbol in no_update]}")
